name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check
      run: |
        perl -c scripts/perl.prov
        perl -c scripts/perl.req
